site_name: EOSC Documentation Hub
docs_dir: resources
theme:
  name: material
  palette:
    primary: custom
  logo: attachments/eosc-beyond-logo.png
  custom_dir: resources/overrides
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - tags
extra_css:
  - stylesheets/extra.css
nav:
  - EOSC Architecture: 
    - EOSC Architecture/index.md
  - Pilot Node: 
    - Pilot Node/index.md
  - Service Provider:
    - Service Provider/index.md
  - End User:
    - End User/index.md
  - Service Portfolio:
    - Service Portfolio/index.md
    - AAI: Service Portfolio/AAI/AAI.md
    - Accounting: Service Portfolio/Accounting/Accounting.md
    - Execution Framework: Service Portfolio/Execution Framework/Execution Framework.md
    - Helpdesk: Service Portfolio/Helpdesk/Helpdesk.md
    - Integration Suite: Service Portfolio/Integration Suite/index.md
    - Messaging: Service Portfolio/Messaging/Messaging.md
    - Monitoring: Service Portfolio/Monitoring/Monitoring.md
    - Accounting: Service Portfolio/Accounting/Accounting.md
    - PID: Service Portfolio/PID/PID.md
    - Resource Catalogue: Service Portfolio/Resource Catalogue/Resource Catalogue.md
    - Order Management: Service Portfolio/Order Management/Order Management.md 
    - Frontend: Service Portfolio/User Space/User Space.md
  - Adapters:
    - Catalogue Adapters: resources/Adapters/Research Product Catalogue/Catalogue.md
    - Accounting Adapters: resources/Adapters/Accounting/Accounting.md
copyright: EOSC Beyond is funded by the European Union Grant Agreement Number 101131875
