site_name: EOSC Documentation Hub
docs_dir: resources
theme:
  name: material
  palette:
    primary: custom
  logo: attachments/eosc-beyond-logo.png
  custom_dir: resources/overrides
  features:
    - navigation.footer
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - tags
extra_css:
  - stylesheets/extra.css
nav:
  - EOSC Architecture: EOSC Architecture/EOSC Architecture.md
  - Pilot Node: Pilot Node/Pilot Node.md
  - Service Provider:
    - Service Provider/Service Provider.md
    - Onboarding: Service Provider/Onboarding.md
  - Service Portfolio:
    - Service Portfolio/Service Portfolio.md
    - Catalogue and Marketplace: Service Portfolio/Catalogue and Marketplace/Catalogue and Marketplace.md
    - Monitoring: Service Portfolio/Monitoring/Monitoring.md
    - Accounting: Service Portfolio/Accounting/Accounting.md
    - AAI: Service Portfolio/AAI/AAI.md
    - Messaging: Service Portfolio/Messaging/Messaging.md
    - Helpdesk: Service Portfolio/Helpdesk/Helpdesk.md
    - Execution Framework: Service Portfolio/Execution Framework/Execution Framework.md
copyright: EOSC Beyond is funded by the European Union Grant Agreement Number 101131875
